setups:
	network:
		exec: riuk/children/core/setups/network.pl
		priority: 10
	data:
		exec: riuk/children/core/setups/data.pl
		priority: 30
parameters:
	data_in:
		mandatory: false
	data_out:
		mandatory: false
	bridge:
		mantatory: true
		value: lxcbr0
	gateway:
		mandatory: true
	iface:
		mandatory: true
		value: eth0
	ipv4:
		mandatory: true
	netmask:
		mandatory: true
		value: 255.255.255.0
	template:
		mandatory: true
		value: flodayalpine -- version 3.4
hooks:
	lxc_deploy_before:
		open_firewall:
			exec: riuk/children/core/hooks/lxc_deploy_before/open_firewall.pl
			priority: 10
	lxc_deploy_after:
		close_firewall:
			exec: riuk/children/core/hooks/lxc_deploy_after/close_firewall.pl
			priority: 10
	lxc_destroy_before:
		clear_filesystem:
			exec: riuk/children/core/hooks/lxc_destroy_before/clear_filesystem.pl
			priority:  10
	lxc_destroy_after:
		update_fstab:
			exec: riuk/children/core/hooks/lxc_destroy_after/update_fstab.pl
			priority: 10
