setups:
	network:
		exec: riuk/children/core/setups/network.pl
		priority: 10
	data:
		exec: riuk/children/core/setups/data.pl
		priority: 30
parameters:
	data_in:
		mandatory: false
	data_out:
		mandatory: false
	bridge:
		mantatory: true
		value: lxcbr0
	gateway:
		mandatory: true
	iface:
		mandatory: true
		value: eth0
	ipv4:
		mandatory: true
	netmask:
		mandatory: true
		value: 255.255.255.0
	template:
		mandatory: true
		value: flodayalpine -- version 3.4
