parameters:
	external_ipv4:
		mandatory: true
		value: 66.66.66.66
	useless_param:
		mandatory: false
		value: 'we dont care'
### This node is commented because the script is only used directly in floday_setup.t !
#setups:
#	folder_creation_on_host:
#		exec: riuk/setups/folder_creation_on_host.pl
#		priority: 10
